name: NPCDialogue
version: 1.0
api-version: 1.15
author: Apple
main: apple.npc.NPCDialogueMain
description: allow the player to teleport using player made paper scrolls
commands:
  make_con_global:
    description: creates a global category for conversations
  make_con_local:
    description: creates a local category for conversations
  make_con:
    description: creates conversation
  make_con_response:
    description: creates a response for a given conversations
  stop_reading:
    description: stops text from being entered by the user
  make_npc:
    description: makes an npc with no conversation associated with it
  npc:
    description: starts a session of editing an npc
  npc_edit_conclusionsToConvo:
    description: starts a session to edit the conclusion to conversation mapping
  ping:
    description: just ping
  npc_respond:
    description: used for responding to an npc (usually done through clicking chat)
