name: NPCDialogue
version: "1.0"
api-version: "1.15"
author: Apple
main: apple.npc.NPCDialogueMain
description: allow the player to teleport using player made paper scrolls
permissions:
  npc.create:
    description: Allows players to create conversations and npcs
    default: op

commands:
  # make commands (obsolete I believe)
  npc_convo_make_global:
    description: starts a session to make a conversation global category
    permission: npc.create
    permission-message: You do not have permission!
  npc_convo_make_local:
    permission: npc.create
    permission-message: You do not have permission!
    description: starts a session to make a conversation local category
  npc_convo_make_convo:
    permission: npc.create
    permission-message: You do not have permission!
    description: starts a session to make something that is related to conversations
  make_con_response:
    permission: npc.create
    permission-message: You do not have permission!
    description: starts an editing session of creating a response in a conversation

  # the main branch of editing stuff
  npc:
    permission: npc.create
    permission-message: You do not have permission!
    description: starts an editing session
  npc_convo_edit:
    permission: npc.create
    description: starts an editing session to edit anything related to conversations
  npc_convo_edit_global:
    permission: npc.create
    description: starts an editing session to edit conversation global categories
  npc_convo_edit_local:
    permission: npc.create
    description: starts an editing session to edit conversation local categories
  npc_convo_edit_convo:
    permission: npc.create
    description: will be starts an editing session to edit a conversation
  npc_convo_edit_response:
    permission: npc.create
    description: starts an editing session to edit a response in a conversation
  npc_convo_edit_response_details:
    permission: npc.create
    description: starts an editing session to edit the details of a response

  # obsolete maybe
  npc_make:
    permission: npc.create
    description: makes a default npc with a name

  # editing details for an npc
  npc_edit:
    permission: npc.create
    description: starts an editing session to edit an npc
  npc_specific_edit:
    permission: npc.create
    description: starts an editing session to edit an alread specified npc
  npc_edit_conclusionsToConvo:
    permission: npc.create
    description: starts an editing session to edit any conclusionsToConversation for an npc
  npc_edit_name:
    permission: npc.create
    description: edits the name of an npc

  # editing details for the boolean part of an npc
  npc_edit_vars:
    permission: npc.create
    description: starts an editing session to edit the vars to conclusion
  npc_edit_vars_specific:
    permission: npc.create
    description: continues an editing session to edit the vars to conclusion given a conclusion to map to
  npc_edit_vars_comp:
    permission: npc.create
    description: continues the editing session inserting a comparison into an expression
  npc_edit_vars_double:
    permission: npc.create
    description: continues the editing session inserting a double expression where an expression used to be
  npc_edit_vars_comp_type:
    permission: npc.create
    description: continues the editing session and asks what type of variable comparison the new expression will be
  npc_edit_vars_comp_local:
    permission: npc.create
    description: continues the editing session and creates a local comparison variable with a given uid
  npc_edit_vars_double_type:
    permission: npc.create
    description: continues the editing session and asks what operators the new double expression will have
  npc_edit_vars_item_isNot:
    permission: npc.create
    description: continues the editing session and asks the player if they want the expression to be a hasItem or not hasItem
  npc_edit_vars_item_trackingtype:
    permission: npc.create
    description: continues the editing session and asks the player what they want to check about the item (local name, custom name)? (always type)
  npc_edit_vars_item_set:
    permission: npc.create
    description: sets the item that the player is holding in thier hand to the variable
  # editing details for the conclusion to convo part of an npc
  npc_edit_concluToConvo_global:
    permission: npc.create
    description: starts an editing session to edit the concluToConvo mapping to get the global category
  npc_edit_concluToConvo_local:
    permission: npc.create
    description: continues an editing session to edit the concluToConvo mapping to get the local category
  npc_edit_concluToConvo_con:
    permission: npc.create
    description: continues an editing session to edit the concluToConvo mapping to get the convo category
  npc_edit_concluToConvo_make:
    permission: npc.create
    description: finishes a session editing to conclusionToConvo for an npc

  # general commands used by the player
  npc_respond:
    permission: npc.create
    description: a command for the user to respond to an npc
  stop_reading:
    permission: npc.create
    description: makes the server finish listening to what the user is saying
  abort_reading:
    permission: npc.create
    description: makes the server stop listening to the player and ignore what was said
  ping:
    permission: npc.create
    description: ping
  npc_write:
    permission: npc.create
    description: writes everything currently in the datastructures into the files
  npc_read:
    permission: npc.create
    description: reads everything currently in the files into the data structures
  npc_force_chat:
    permission: npc.create
    description: makes a player say something in chat

  # deal with normal post response editing
  npc_convo_edit_response_postresponse_make:
    description: starts an editing session to edit a postResponse for a response
    permission: npc.create
  npc_convo_edit_response_post_local:
    description: continues an editing session to edit the local redirect part of a postResponse for a response
    permission: npc.create
  npc_convo_edit_response_post_convo:
    permission: npc.create
    description: continues an editing session to edit the convo redirect part of a postResponse for a response
  npc_convo_edit_response_set:
    permission: npc.create
    description: sets the global.local.convo for resposne
  npc_convo_edit_response_post_bool:
    permission: npc.create
    description: continues an editing session to edit the boolean requirement for this response option

  # post response details editing
  npc_convo_edit_response_postresponse:
    description: displays a menu for the player to decide what they want to change about the current post response
    permission: npc.create
  npc_convo_delete_post_response:
    description: deletes a postresponse
    permission: npc.create
  npc_convo_edit_response_reqs:
    permission: npc.create
    description: starts an editing session to edit the boolean expression (redirect requirements) of a post response
  npc_convo_edit_response_var_change:
    description: continues an editing session and requests the user to enter a global category for a variable change
    permission: npc.create
  npc_convo_edit_response_var_change_local:
    description: continues an editing session and requests the user to enter a variable name for a variable change
    permission: npc.create
  npc_convo_edit_response_var_change_val:
    permission: npc.create
    description: continues an editing session and requests the user to enter a variable value for a variable change

  # will be commands
  npc_convo_edit_local_name:
    description: will be edits the name of a local category
    permission: npc.create
  npc_convo_edit_convo_name:
    description: will be edits the name of a conversation
    permission: npc.create
  npc_convo_edit_convo_text:
    description: will be edits the text of a conversation
    permission: npc.create
  npc_convo_edit_convo_imm:
    description: will be edits the immediateConvo of a conversation
    permission: npc.create
  npc_convo_edit_response_preResponse:
    description: will be starts an editing session to edit the boolean expression that is the preResponseRequirements
    permission: npc.create
  npc_convo_edit_response_text:
    description: will be starts an editing session to edit the text of the response
    permission: npc.create
  npc_convo_edit_response_default:
    description: will be starts an editing session to edit the default_response
    permission: npc.create
  npc_getuid:
    description: gets uids around a player
    permission: npc.create
