name: NPCDialogue
version: 1.0
api-version: 1.15
author: Apple
main: apple.npc.NPCDialogueMain
description: allow the player to teleport using player made paper scrolls
commands:
  make_con_global:
    description: creates a global category for conversations
  make_con_local:
    description: creates a local category for conversations
  make_con:
    description: creates conversation
  make_con_response:
    description: creates a response for a given conversations
  con_stop:
    description: stops text from being entered by the user
  make_npc:
    description: makes an npc with no conversation associated with it
  ping:
    description: just ping
