name: NPCDialogue
version: "1.0"
api-version: "1.15"
author: Apple
main: apple.npc.NPCDialogueMain
description: allow the player to teleport using player made paper scrolls
commands:
  npc_convo_make_global:
    description: starts a session to make a conversation global category
  npc_convo_make_local:
    description: starts a session to make a conversation local category
  npc_convo_make_convo:
    description: starts a session to make something that is related to conversations
  make_con_response:
    description: starts an editing session of creating a response in a conversation


  npc:
    description: starts an editing session

  npc_convo_edit:
    description: starts an editing session to edit anything related to conversations
  npc_convo_edit_global:
    description: starts an editing session to edit conversation global categories
  npc_convo_edit_local:
    description: starts an editing session to edit conversation local categories
  npc_convo_edit_convo:
    description: will be starts an editing session to edit a conversation
  npc_convo_edit_response:
    description: starts an editing session to edit a response in a conversation
  npc_convo_edit_response_details:
    description: starts an editing session to edit the details of a response


  npc_make:
    description: makes a default npc with a name

  npc_edit:
    description: starts an editing session to edit an npc
  npc_edit_conclusionsToConvo:
    description: starts an editing session to edit any conclusionsToConversation for an npc


  npc_respond:
    description: a command for the user to respond to an npc
  stop_reading:
    description: makes the server stop listening to what the user is saying
  ping:
    description: ping


  npc_convo_edit_local_name:
    description: will be edits the name of a local category
  npc_convo_edit_convo_name:
    description: will be edits the name of a conversation
  npc_convo_edit_convo_text:
    description: will be edits the text of a conversation
  npc_convo_edit_convo_imm:
    description: will be edits the immediateConvo of a conversation
  npc_convo_edit_response_preResponse:
    description: will be starts an editing session to edit the boolean expression that is the preResponseRequirements
  npc_convo_edit_response_text:
    description: will be starts an editing session to edit the text of the response
  npc_convo_edit_response_postresponse:
    description: will be starts an editing session to edit the boolean expression that is the postResponseRequirements
  npc_convo_edit_response_default:
    description: will be starts an editing session to edit the default_response
